/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FibonacciOBJ;

/**
 *
 * @author Fer
 */
public class AppFibonacci extends javax.swing.JFrame {

    /**
     * Creates new form AppFibonacci
     */
    public AppFibonacci() {
        initComponents();
        
    }
    Fibonacci_clase Fibonacci = new Fibonacci_clase();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ejecutar_btn = new javax.swing.JButton();
        btn_serie = new javax.swing.JButton();
        txt_valor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_termino = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ejecutar_btn.setText("Ejecutar");
        Ejecutar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejecutar_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Ejecutar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        btn_serie.setText("Mostrar Serie");
        getContentPane().add(btn_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));
        getContentPane().add(txt_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("valor en esa posicion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, 20));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel2.setText("Termino a buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        getContentPane().add(txt_termino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ejecutar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejecutar_btnActionPerformed
        // TODO add your handling code here:
        
        int termino = Integer.parseInt(txt_termino.getText());
        
        txt_valor.setText(String.valueOf(Fibonacci.FiboValor(termino)));
    }//GEN-LAST:event_Ejecutar_btnActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFibonacci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejecutar_btn;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_serie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_termino;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
